# Wrangler configuration for NuxtHub deployment
name = "pingtopass-nuxt"
compatibility_date = "2024-09-06"
compatibility_flags = ["nodejs_compat"]

# Secrets to be set via CLI or dashboard:
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET 
# NUXT_SESSION_PASSWORD
# TURSO_DATABASE_URL
# TURSO_AUTH_TOKEN
# OPENROUTER_API_KEY
# LANGCHAIN_API_KEY
# LANGSMITH_API_KEY