# Wrangler configuration for Cloudflare deployment
name = "pingtopass-nuxt"
compatibility_date = "2024-09-06"

# Build configuration
[build]
command = "pnpm run build"

# Environment variables (these will be set in Cloudflare dashboard)
[vars]
APP_NAME = "PingToPass"
BASE_URL = "https://pingtopass.com"

# KV namespaces for session storage
[[kv_namespaces]]
binding = "KV"
id = "pingtopass_kv"

# R2 bucket for file storage
[[r2_buckets]]
binding = "BLOB"
bucket_name = "pingtopass-files"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Routes configuration will be set up later for custom domain

# Pages configuration
[pages]
build_output_dir = ".output/public"

# D1 Database (not used - we're using Turso)
# [[d1_databases]]
# binding = "DB"
# database_name = "pingtopass"

# Compatibility flags for Cloudflare Workers
compatibility_flags = ["nodejs_compat"]

# These settings will be configured through Cloudflare Pages dashboard