name = "pingtopass-mcp-server"
main = "index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables for production
[env.production]
name = "pingtopass-mcp-server-prod"

[env.production.vars]
ENVIRONMENT = "production"

# Environment variables for staging
[env.staging]
name = "pingtopass-mcp-server-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

# Analytics Engine binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "pingtopass_mcp_analytics"

# Routes for custom domain (disabled until domain is configured)
# [[routes]]
# pattern = "mcp.pingtopass.com/*"
# zone_name = "pingtopass.com"

# Limits
[limits]
cpu_ms = 30000